const TR = true;
const FL = false;
const ONE = 1;
const ZR = 0;
console.log(TR === TR);
console.log(TR === FL);
console.log(TR === ONE);
console.log(TR === ZR);
console.log(FL === TR);
console.log(FL === FL);
console.log(FL === ONE);
console.log(FL === ZR);
console.log(ONE === TR);
console.log(ONE === FL);
console.log(ONE === ONE);
console.log(ONE === ZR);
console.log(ZR === TR);
console.log(ZR === FL);
console.log(ZR === ONE);
console.log(ZR === ZR);